In [3]:
import tensorflow as tf
import numpy as np
import os
import pandas as pd

In [4]:
tf.__version__

'2.20.0'

In [5]:
train_dir = r"train"
test_dir = r"test"
os.path.exists(train_dir)

True

In [6]:
df = pd.read_csv('Training_set.csv')
df.shape

(6499, 2)

In [7]:
train_ds = tf.keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    directory=test_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)


Found 6499 files.
Found 2786 files.


In [8]:
lmao = next(iter(train_ds))
lmao

<tf.Tensor: shape=(67, 128, 128, 3), dtype=float32, numpy=
array([[[[1.06984375e+02, 1.61984375e+02, 3.39843750e+01],
         [1.08046875e+02, 1.63046875e+02, 3.49531250e+01],
         [1.09796875e+02, 1.64796875e+02, 3.49531250e+01],
         ...,
         [9.20312500e+01, 1.42625000e+02, 1.50000000e+00],
         [9.64062500e+01, 1.43500000e+02, 1.50000000e+00],
         [1.01875000e+02, 1.46875000e+02, 3.87500000e+00]],

        [[1.10375000e+02, 1.63375000e+02, 3.32812500e+01],
         [1.08984375e+02, 1.64000000e+02, 3.39531250e+01],
         [1.09859375e+02, 1.64984375e+02, 3.46093750e+01],
         ...,
         [9.01406250e+01, 1.40890625e+02, 0.00000000e+00],
         [9.37500000e+01, 1.42750000e+02, 0.00000000e+00],
         [9.82500000e+01, 1.46250000e+02, 2.25000000e+00]],

        [[1.10703125e+02, 1.63703125e+02, 3.12031250e+01],
         [1.10734375e+02, 1.64000000e+02, 3.19843750e+01],
         [1.11609375e+02, 1.64984375e+02, 3.11093750e+01],
         ...,
         [

In [9]:
uniq = np.array(df['label'].unique())

In [10]:
for i in range (uniq.size):
    uniq[i] = i

In [11]:
unique = np.array(df['label'].unique())

In [12]:
uniqi = dict(zip(unique, uniq))
uniqi

{'SOUTHERN DOGFACE': 0,
 'ADONIS': 1,
 'BROWN SIPROETA': 2,
 'MONARCH': 3,
 'GREEN CELLED CATTLEHEART': 4,
 'CAIRNS BIRDWING': 5,
 'EASTERN DAPPLE WHITE': 6,
 'RED POSTMAN': 7,
 'MANGROVE SKIPPER': 8,
 'BLACK HAIRSTREAK': 9,
 'CABBAGE WHITE': 10,
 'RED ADMIRAL': 11,
 'PAINTED LADY': 12,
 'PAPER KITE': 13,
 'SOOTYWING': 14,
 'PINE WHITE': 15,
 'PEACOCK': 16,
 'CHECQUERED SKIPPER': 17,
 'JULIA': 18,
 'COMMON WOOD-NYMPH': 19,
 'BLUE MORPHO': 20,
 'CLOUDED SULPHUR': 21,
 'STRAITED QUEEN': 22,
 'ORANGE OAKLEAF': 23,
 'PURPLISH COPPER': 24,
 'ATALA': 25,
 'IPHICLUS SISTER': 26,
 'DANAID EGGFLY': 27,
 'LARGE MARBLE': 28,
 'PIPEVINE SWALLOW': 29,
 'BLUE SPOTTED CROW': 30,
 'RED CRACKER': 31,
 'QUESTION MARK': 32,
 'CRIMSON PATCH': 33,
 'BANDED PEACOCK': 34,
 'SCARCE SWALLOW': 35,
 'COPPER TAIL': 36,
 'GREAT JAY': 37,
 'INDRA SWALLOW': 38,
 'VICEROY': 39,
 'MALACHITE': 40,
 'APPOLLO': 41,
 'TWO BARRED FLASHER': 42,
 'MOURNING CLOAK': 43,
 'TROPICAL LEAFWING': 44,
 'POPINJAY': 45,
 'ORANGE TIP':

In [13]:
uniqi = dict(zip(unique, uniq))
label_arr = []
for item in df['label']:
    label_arr.append(uniqi[item])
label_arr = tf.convert_to_tensor(label_arr)
label_arr

<tf.Tensor: shape=(6499,), dtype=int32, numpy=array([ 0,  1,  2, ..., 41, 60, 25], shape=(6499,), dtype=int32)>

In [14]:

# train_ds_v2 = tf.keras.utils.image_dataset_from_directory(
#     directory=train_dir,
#     labels=label_arr,
#     label_mode="int",
#     batch_size=67,
#     shuffle=True,
#     color_mode='rgb',
#     image_size = (128,128)
# )

label_arr

<tf.Tensor: shape=(6499,), dtype=int32, numpy=array([ 0,  1,  2, ..., 41, 60, 25], shape=(6499,), dtype=int32)>

In [18]:
# Move to another folder so it won't be such a mess 💀
os.chdir('c:\\Users\\Tran Vu\\OneDrive\\Documents\\TestingPrj\\butterfly_classification\\image_categorize')
os.getcwd()

# Process to create a file with each name the anim
for labels in uniqi.keys():
    os.mkdir(labels)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'SOUTHERN DOGFACE'