In [2]:
import tensorflow as tf
import numpy as np
import os
import pandas as pd

In [3]:
tf.__version__

'2.20.0'

In [4]:
train_dir = r"train"
test_dir = r"test"
os.path.exists(train_dir)

True

In [5]:
df = pd.read_csv('Training_set.csv')
df.shape

(6499, 2)

In [6]:
train_ds = tf.keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    directory=test_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)


Found 6499 files.
Found 2786 files.


In [7]:
lmao = next(iter(train_ds))
lmao

<tf.Tensor: shape=(67, 128, 128, 3), dtype=float32, numpy=
array([[[[1.19875000e+02, 1.50875000e+02, 4.68750000e+01],
         [1.17250000e+02, 1.49250000e+02, 4.22500000e+01],
         [1.14625000e+02, 1.46625000e+02, 3.96250000e+01],
         ...,
         [1.41718750e+02, 1.64078125e+02, 7.06250000e+01],
         [1.38000000e+02, 1.63750000e+02, 6.71250000e+01],
         [1.35625000e+02, 1.63156250e+02, 6.38593750e+01]],

        [[1.20453125e+02, 1.53453125e+02, 4.64531250e+01],
         [1.17984375e+02, 1.50984375e+02, 4.59843750e+01],
         [1.15250000e+02, 1.48250000e+02, 4.33593750e+01],
         ...,
         [1.38609375e+02, 1.62859375e+02, 6.82656250e+01],
         [1.36859375e+02, 1.62750000e+02, 6.58593750e+01],
         [1.34031250e+02, 1.63375000e+02, 6.33750000e+01]],

        [[1.21875000e+02, 1.54875000e+02, 4.78750000e+01],
         [1.17109375e+02, 1.52625000e+02, 4.69687500e+01],
         [1.15906250e+02, 1.48359375e+02, 4.66406250e+01],
         ...,
         [

In [8]:
uniq = np.array(df['label'].unique())

In [9]:
for i in range (uniq.size):
    uniq[i] = i

In [10]:
unique = np.array(df['label'].unique())

In [11]:
uniqi = dict(zip(unique, uniq))

In [12]:
uniqi = dict(zip(unique, uniq))
label_arr = []
for item in df['label']:
    label_arr.append(uniqi[item])
label_arr = tf.convert_to_tensor(label_arr)
label_arr

<tf.Tensor: shape=(6499,), dtype=int32, numpy=array([ 0,  1,  2, ..., 41, 60, 25], shape=(6499,), dtype=int32)>

In [13]:
train_ds_v2 = tf.keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels=label_arr,
    label_mode="int",
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)

TypeError: Cannot convert 'inferred' to EagerTensor of dtype int32