In [1]:
import tensorflow as tf
import numpy as np
import os
import pandas as pd

In [2]:
train_dir = r"train"
test_dir = r"test"
os.path.exists(train_dir)

True

In [3]:
df = pd.read_csv('Training_set.csv')
df.shape

(6499, 2)

In [4]:
train_ds = tf.keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    directory=test_dir,
    labels=None,
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)


Found 6499 files.
Found 2786 files.


In [5]:
lmao = next(iter(train_ds))
lmao

<tf.Tensor: shape=(67, 128, 128, 3), dtype=float32, numpy=
array([[[[171.      , 166.76562 ,  80.46875 ],
         [167.875   , 165.75    ,  83.25    ],
         [166.125   , 164.      ,  88.5     ],
         ...,
         [158.54688 , 175.79688 ,  95.671875],
         [157.125   , 176.125   ,  95.125   ],
         [155.625   , 176.625   ,  97.625   ]],

        [[171.625   , 167.625   ,  79.28125 ],
         [167.98438 , 165.85938 ,  82.890625],
         [166.23438 , 164.10938 ,  88.359375],
         ...,
         [158.10938 , 175.35938 ,  95.234375],
         [157.125   , 176.125   ,  95.125   ],
         [156.875   , 175.875   ,  96.875   ]],

        [[171.625   , 167.625   ,  77.53125 ],
         [167.875   , 165.85938 ,  81.140625],
         [165.35938 , 163.34375 ,  85.84375 ],
         ...,
         [158.98438 , 176.01562 ,  96.      ],
         [158.      , 175.25    ,  95.125   ],
         [156.875   , 174.125   ,  96.      ]],

        ...,

        [[165.79688 , 164.79688 ,

In [6]:
uniq = np.array(df['label'].unique())

In [7]:
for i in range (uniq.size):
    uniq[i] = i

In [8]:
unique = np.array(df['label'].unique())

In [9]:
uniqi = dict(zip(unique, uniq))

In [10]:
uniqi = dict(zip(unique, uniq))
label_arr = []
for item in df['label']:
    label_arr.append(uniqi[item])
label_arr = tf.convert_to_tensor(label_arr)
label_arr

<tf.Tensor: shape=(6499,), dtype=int32, numpy=array([ 0,  1,  2, ..., 41, 60, 25], shape=(6499,), dtype=int32)>

In [11]:
train_ds_v2 = tf.keras.utils.image_dataset_from_directory(
    directory=train_dir,
    labels=label_arr,
    label_mode="int",
    batch_size=67,
    shuffle=True,
    color_mode='rgb',
    image_size = (128,128)
)

TypeError: Cannot convert 'inferred' to EagerTensor of dtype int32